# Generated by Django 4.2 on 2023-04-23 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id_recette', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_recette', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=50)),
                ('ingredients', models.TextField()),
                ('discription', models.TextField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Recette',
            },
        ),
    ]
