# Generated by Django 4.2 on 2023-04-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='image',
            field=models.ImageField(default='default-image.jpg', upload_to='images/'),
        ),
    ]
