# Generated by Django 4.2 on 2023-04-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetteapp', '0002_recette_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='id_recette',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
