# Generated by Django 4.2 on 2023-05-02 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recetteapp', '0007_comment_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteRecette',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetteapp.recette')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorite_recette',
            },
        ),
    ]
